# Generated by Django 5.2.1 on 2025-06-23 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimAICCustomer',
            fields=[
                ('cust_id', models.AutoField(help_text='Main identifier of a user', primary_key=True, serialize=False, verbose_name='Customer ID')),
                ('cust_secure_id', models.CharField(editable=False, help_text='Main identifier of a customer', max_length=9, verbose_name='Customer Secure ID')),
                ('cust_name', models.CharField(help_text='Name of customer', max_length=255, verbose_name='Customer Name')),
                ('street', models.CharField(help_text='Street portion of an address', max_length=255, verbose_name='Street')),
                ('city', models.CharField(help_text='City that customer is based in', max_length=100, verbose_name='City')),
                ('st_abrv', models.CharField(help_text='State that customer is based in', max_length=2, verbose_name='State Abbreviation')),
                ('zip_code', models.IntegerField(help_text='Zip code of the customer address', verbose_name='Zip Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date customer was added to the system', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update of record', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AIC Customer',
                'verbose_name_plural': 'AIC Customers',
                'db_table': 'dim_aic_customer',
            },
        ),
        migrations.CreateModel(
            name='DimAICUser',
            fields=[
                ('user_id', models.AutoField(help_text='Main identifier of a user', primary_key=True, serialize=False, verbose_name='User ID')),
                ('username', models.CharField(help_text='Username of user', max_length=8, verbose_name='Username')),
                ('first_name', models.CharField(help_text='First name of user', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Last name of user', max_length=100, verbose_name='Last Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date user was added to the system', verbose_name='Created At')),
                ('input_user', models.IntegerField(help_text='User ID of the user that added the new user.', verbose_name='Input User')),
                ('cust_id', models.ForeignKey(help_text='Customer that the user is under', on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID')),
            ],
            options={
                'verbose_name': 'AIC User',
                'verbose_name_plural': 'AIC Users',
                'db_table': 'dim_aic_user',
            },
        ),
        migrations.AddField(
            model_name='dimaiccustomer',
            name='input_user',
            field=models.ForeignKey(blank=True, help_text='User ID of the user that added the contact (foreign key constraint removed)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser', verbose_name='Input User'),
        ),
        migrations.CreateModel(
            name='DimAICClient',
            fields=[
                ('client_id', models.AutoField(help_text='Unique identifier for each client', primary_key=True, serialize=False, verbose_name='Client ID')),
                ('client_name', models.CharField(help_text='Name of client', max_length=255, verbose_name='Client Name')),
                ('street', models.CharField(help_text='Street portion of an address', max_length=255, verbose_name='Street')),
                ('city', models.CharField(help_text='City that client is based in', max_length=100, verbose_name='City')),
                ('st_abrv', models.CharField(help_text='State that client is based in', max_length=2, verbose_name='State Abbreviation')),
                ('zip_code', models.IntegerField(help_text='Zip code of the client address', verbose_name='Zip Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date client was added to the system', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update of record', verbose_name='Updated At')),
                ('cust_id', models.ForeignKey(help_text='Main identifier of a customer', on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID')),
                ('input_user', models.ForeignKey(blank=True, help_text='Customer user that created client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser')),
            ],
            options={
                'verbose_name': 'AIC Client',
                'verbose_name_plural': 'AIC Clients',
                'db_table': 'dim_aic_client',
            },
        ),
        migrations.CreateModel(
            name='DimAICContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='Main identifier of a user', verbose_name='User ID')),
                ('contact_typ', models.CharField(help_text='Either email or phone contact identifier', max_length=5, verbose_name='Contact Type')),
                ('contact', models.CharField(help_text='Actual email or phone number of customer, client, or user', max_length=100, verbose_name='Contact')),
                ('reg_flg', models.BooleanField(help_text='Identifies whether the contact was added during registration', verbose_name='Registration Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date client was added to the system', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update of record', verbose_name='Updated At')),
                ('cust_id', models.ForeignKey(help_text='Customer that the user is under', on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID')),
                ('input_user', models.ForeignKey(blank=True, help_text='User ID of the user that added the contact (foreign key constraint removed)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser', verbose_name='Input User')),
            ],
            options={
                'verbose_name': 'AIC Contact',
                'verbose_name_plural': 'AIC Contacts',
                'db_table': 'dim_aic_Contact',
                'unique_together': {('cust_id', 'user_id')},
            },
        ),
    ]
