# Generated by Django 5.2.1 on 2025-06-25 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimAICCustomer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Customer ID')),
                ('cust_secure_id', models.CharField(editable=False, max_length=9, verbose_name='Customer Secure ID')),
                ('cust_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('st_abrv', models.CharField(max_length=2, verbose_name='State Abbreviation')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AIC Customer',
                'verbose_name_plural': 'AIC Customers',
                'db_table': 'dim_aic_customer',
            },
        ),
        migrations.CreateModel(
            name='DimAICUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('username', models.CharField(max_length=8, verbose_name='Username')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID')),
            ],
            options={
                'verbose_name': 'AIC User',
                'verbose_name_plural': 'AIC Users',
                'db_table': 'dim_aic_user',
            },
        ),
        migrations.AddField(
            model_name='dimaiccustomer',
            name='input_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser', verbose_name='Input User'),
        ),
        migrations.CreateModel(
            name='DimAICClient',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Client ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Client Name')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('st_abrv', models.CharField(max_length=2, verbose_name='State Abbreviation')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID')),
                ('input_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser')),
            ],
            options={
                'verbose_name': 'AIC Client',
                'verbose_name_plural': 'AIC Clients',
                'db_table': 'dim_aic_client',
            },
        ),
        migrations.CreateModel(
            name='DimAICContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
                ('contact_typ', models.CharField(max_length=5, verbose_name='Contact Type')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact')),
                ('reg_flg', models.BooleanField(verbose_name='Registration Flag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID')),
                ('input_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser', verbose_name='Input User')),
            ],
            options={
                'verbose_name': 'AIC Contact',
                'verbose_name_plural': 'AIC Contacts',
                'db_table': 'dim_aic_contact',
                'unique_together': {('cust_id', 'user_id')},
            },
        ),
    ]
