# Generated by Django 5.2.1 on 2025-07-01 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimaicclient',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RenameField(
            model_name='dimaicclient',
            old_name='st_abrv',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='dimaiccustomer',
            old_name='cust_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='dimaiccustomer',
            old_name='cust_name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='dimaiccustomer',
            old_name='cust_secure_id',
            new_name='customer_secure_id',
        ),
        migrations.RenameField(
            model_name='dimaiccustomer',
            old_name='st_abrv',
            new_name='street_abrevation',
        ),
        migrations.RemoveField(
            model_name='dimaicclient',
            name='cust_id',
        ),
        migrations.AlterUniqueTogether(
            name='dimaiccontact',
            unique_together={('client_id', 'contact_type')},
        ),
        migrations.AddField(
            model_name='dimaicclient',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigend_clients', to='user.dimaicuser', verbose_name='Assigned User'),
        ),
        migrations.AddField(
            model_name='dimaicclient',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='user.dimaiccustomer', verbose_name='Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimaiccontact',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.dimaicclient', verbose_name='Client ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimaiccontact',
            name='contact_type',
            field=models.CharField(choices=[('phone', 'phone'), ('email', 'email')], default=1, max_length=5, verbose_name='Contact Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimaiccustomer',
            name='invite_token',
            field=models.CharField(blank=True, help_text='Invite token for registration', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dimaiccustomer',
            name='registration_complete',
            field=models.BooleanField(default=False, help_text='Becomes True after first SSO login'),
        ),
        migrations.AddField(
            model_name='dimaiccustomer',
            name='user',
            field=models.OneToOneField(default=1, help_text='Link to Django user for authentication and permissions', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Linked Django User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimaicuser',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='User Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='input_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Input User (Admin)'),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='input_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Input User'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='input_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Input User'),
        ),
        migrations.CreateModel(
            name='DimAICClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('COA', 'Chart of Accounts'), ('VENDOR_LIST', 'Vendor List'), ('GL_HISTORY', 'GL History')], max_length=20, verbose_name='Document Type')),
                ('file', models.FileField(help_text='File will be stored in local media folder. Future support for S3/Azure.', upload_to='client_documents/', verbose_name='Document File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.dimaicclient', verbose_name='Client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'db_table': 'client_documents',
            },
        ),
        migrations.RemoveField(
            model_name='dimaiccontact',
            name='contact_typ',
        ),
        migrations.RemoveField(
            model_name='dimaiccontact',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='dimaiccontact',
            name='user_id',
        ),
    ]
