# Generated by Django 5.2.1 on 2025-06-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_dimaiccontact_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicclient',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='client_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='input_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='st_abrv',
            field=models.CharField(max_length=2, verbose_name='State Abbreviation'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='zip_code',
            field=models.IntegerField(verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='contact_typ',
            field=models.CharField(max_length=5, verbose_name='Contact Type'),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='input_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser', verbose_name='Input User'),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='reg_flg',
            field=models.BooleanField(verbose_name='Registration Flag'),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='user_id',
            field=models.IntegerField(verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='cust_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='cust_name',
            field=models.CharField(max_length=255, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='cust_secure_id',
            field=models.CharField(editable=False, max_length=9, verbose_name='Customer Secure ID'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='input_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser', verbose_name='Input User'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='st_abrv',
            field=models.CharField(max_length=2, verbose_name='State Abbreviation'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='dimaiccustomer',
            name='zip_code',
            field=models.IntegerField(verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='dimaicuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dimaicuser',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='dimaicuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='dimaicuser',
            name='input_user',
            field=models.IntegerField(verbose_name='Input User'),
        ),
        migrations.AlterField(
            model_name='dimaicuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='dimaicuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='dimaicuser',
            name='username',
            field=models.CharField(max_length=8, verbose_name='Username'),
        ),
    ]
