# Generated by Django 5.2.1 on 2025-07-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_dimaicclient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimaiccustomer',
            name='street_abrevation',
        ),
        migrations.AddField(
            model_name='dimaiccustomer',
            name='state',
            field=models.CharField(default=1, max_length=2, verbose_name='State'),
            preserve_default=False,
        ),
    ]
