# Generated by Django 4.2.23 on 2025-07-19 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_dimaiccustomer_invite_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimaicclient',
            options={'verbose_name': 'AIC Client', 'verbose_name_plural': 'AIC Clients'},
        ),
        migrations.AlterUniqueTogether(
            name='dimaiccontact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dimaiccontact',
            name='contact_email',
            field=models.CharField(default=1, max_length=100, verbose_name='Contact Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimaiccontact',
            name='contact_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Contact Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimaiccontact',
            name='contact_phone',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7 to 15 digits, optional leading +)', regex='^\\+?\\d{7,15}$')], verbose_name='Contact Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='user.dimaicclient', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dimaiccontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='dimaiccontact',
            unique_together={('client_id', 'contact_email')},
        ),
        migrations.RemoveField(
            model_name='dimaiccontact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='dimaiccontact',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='dimaiccontact',
            name='input_user',
        ),
        migrations.RemoveField(
            model_name='dimaiccontact',
            name='reg_flg',
        ),
    ]
