# Generated by Django 5.2.1 on 2025-06-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_dimaicclient_city_alter_dimaicclient_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimaicuser',
            name='input_user',
        ),
        migrations.AddField(
            model_name='dimaicuser',
            name='input_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser'),
        ),
    ]
