# Generated by Django 5.2.1 on 2025-06-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_dimaicuser_input_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimaicuser',
            name='input_user_id',
        ),
    ]
