# Generated by Django 4.2.23 on 2025-07-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_id_dimaicclient_temp_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimaicclient',
            old_name='temp_client_id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='dimaicclient',
            old_name='temp_id',
            new_name='id',
        ),
    ]
