# Generated by Django 5.2.1 on 2025-07-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_temp_client_id_dimaicclient_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicclient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State Abbreviation'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='dimaicclient',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='dimaicclientdocument',
            name='document_type',
            field=models.CharField(choices=[('chart_of_account', 'Chart of Accounts'), ('vendor_list', 'Vendor List'), ('gl_history', 'GL History')], max_length=20, verbose_name='Document Type'),
        ),
    ]
