# Generated by Django 4.2.23 on 2025-07-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_dimaicaccountant_remove_dimaicclient_assigned_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicaccountant',
            name='first_name',
            field=models.CharField(max_length=72, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='dimaicaccountant',
            name='last_name',
            field=models.CharField(max_length=72, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='dimaicaccountant',
            name='username',
            field=models.CharField(max_length=72, verbose_name='Username'),
        ),
    ]
