# Generated by Django 4.2.23 on 2025-07-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_dimaicaccountant_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicaccountant',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountants', to='user.dimaiccustomer', verbose_name='Customer ID'),
        ),
    ]
