# Generated by Django 4.2.23 on 2025-07-30 13:47

from django.db import migrations, models
import user.models.dim_aic_client_model


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_dimaicaccountant_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicclientdocument',
            name='file',
            field=models.FileField(help_text='File will be stored in Azure Blob Storage with customer/client folder structure.', max_length=500, upload_to=user.models.dim_aic_client_model.upload_to_customer_client_folder, verbose_name='Document File'),
        ),
    ]
