# Generated by Django 4.2.23 on 2025-07-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_dimaicclientdocument_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimaiccustomer',
            old_name='customer_id',
            new_name='id',
        ),
    ]
