# Generated by Django 4.2.23 on 2025-11-21 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_customer_id_dimaiccustomer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaiccontact',
            name='contact_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7 to 15 digits, optional leading +)', regex='^(?:\\d{10,15}|\\d{3}-\\d{3}-\\d{4})$')], verbose_name='Contact Phone'),
        ),
    ]
