# Generated by Django 4.2.23 on 2026-02-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_dimaicreviewer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimaicaccountant',
            options={'verbose_name': 'Accountant', 'verbose_name_plural': 'Accountants'},
        ),
        migrations.AlterModelOptions(
            name='dimaicassistant',
            options={'verbose_name': 'Assistant', 'verbose_name_plural': 'Assistants'},
        ),
        migrations.AlterModelOptions(
            name='dimaicclient',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='dimaiccontact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='dimaiccustomer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelTable(
            name='dimaicaccountant',
            table='accountant',
        ),
        migrations.AlterModelTable(
            name='dimaicassistant',
            table='assistant',
        ),
        migrations.AlterModelTable(
            name='dimaicclient',
            table='client',
        ),
        migrations.AlterModelTable(
            name='dimaiccontact',
            table='contact',
        ),
        migrations.AlterModelTable(
            name='dimaiccustomer',
            table='customer',
        ),
    ]
