# Generated by Django 4.2.23 on 2025-08-06 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicinputfileattributes',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_file_attributes', to='account.dimaicglacct', verbose_name='GL Account'),
        ),
        migrations.AlterField(
            model_name='dimaicinputfileattributes',
            name='offset_gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offset_input_file_attributes', to='account.dimaicglacct', verbose_name='Offset GL Account'),
        ),
    ]
