# Generated by Django 4.2.23 on 2025-08-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_dimaicjetemplateattribute_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimaicjetemplateheader',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description or comments about the Template', null=True, verbose_name='Description'),
        ),
    ]
