# Generated by Django 4.2.23 on 2025-08-10 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0015_rename_customer_id_dimaiccustomer_id'),
        ('account', '0004_dimaicjetemplateheader_description'),
    ]

    operations = [
         migrations.CreateModel(
            name='FactAICMonthlyAccounting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Monthly Accounting ID')),
                ('month', models.IntegerField(help_text='Month (1-12)', verbose_name='Month')),
                ('year', models.IntegerField(help_text='Year (e.g., 2025)', verbose_name='Year')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_accounting', to='user.dimaicclient', verbose_name='Client')),
                ('created_by', models.ForeignKey(help_text='User who initiated this accounting session', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Monthly Accounting',
                'verbose_name_plural': 'Monthly Accounting Sessions',
                'db_table': 'fact_aic_monthly_accounting',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'month', 'year')},
            },
        ),
    ]
