# Generated by Django 4.2.23 on 2025-08-17 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_monthlyaccountingdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyaccountingdocument',
            name='control_item',
            field=models.JSONField(blank=True, help_text='Control totals and summary information extracted from document', null=True, verbose_name='Control Totals'),
        ),
        migrations.CreateModel(
            name='MonthlyDocumentBankLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='Page number where this line item was found', verbose_name='Page Number')),
                ('line_number', models.IntegerField(help_text='Line number within the page', verbose_name='Line Number')),
                ('date', models.CharField(blank=True, help_text='Date of the transaction as extracted from document', max_length=50, null=True, verbose_name='Transaction Date')),
                ('description', models.TextField(help_text='Description/narrative of the transaction', verbose_name='Description')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Transaction amount (always positive, type indicates debit/credit)', max_digits=15, null=True, verbose_name='Amount')),
                ('transaction_type', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='Whether this is a debit or credit transaction', max_length=10, null=True, verbose_name='Transaction Type')),
                ('debit_amount', models.CharField(blank=True, help_text='Raw debit amount as extracted from document', max_length=50, null=True, verbose_name='Debit Amount (Raw)')),
                ('credit_amount', models.CharField(blank=True, help_text='Raw credit amount as extracted from document', max_length=50, null=True, verbose_name='Credit Amount (Raw)')),
                ('is_check_transaction', models.BooleanField(default=False, help_text='Whether this line item represents a check transaction', verbose_name='Is Check Transaction')),
                ('check_number', models.CharField(blank=True, help_text='Check number if this is a check transaction', max_length=50, null=True, verbose_name='Check Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='account.monthlyaccountingdocument', verbose_name='Monthly Document')),
                ('gl_account', models.ForeignKey(blank=True, help_text='GL account assigned through classification pipeline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_document_line_items', to='account.dimaicglacct', verbose_name='GL Account')),
                ('offset_gl_account', models.ForeignKey(blank=True, help_text='Offset GL account for double-entry booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_document_offset_line_items', to='account.dimaicglacct', verbose_name='Offset GL Account')),
            ],
            options={
                'verbose_name': 'Monthly Document Line Item',
                'verbose_name_plural': 'Monthly Document Line Items',
                'db_table': 'monthly_document_line_item',
                'ordering': ['page_number', 'line_number'],
                'unique_together': {('document', 'page_number', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyDocumentBankCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='Page number where this check was found', verbose_name='Page Number')),
                ('amount', models.CharField(help_text='Check amount as extracted from check image', max_length=100, verbose_name='Amount')),
                ('payee', models.TextField(blank=True, help_text='Payee name from check', null=True, verbose_name='Payee')),
                ('memo', models.TextField(blank=True, help_text='Memo line from check', null=True, verbose_name='Memo')),
                ('clearing_date', models.CharField(blank=True, help_text='Date when check cleared', max_length=50, null=True, verbose_name='Clearing Date')),
                ('passing_date', models.CharField(blank=True, help_text='Date when check was processed', max_length=50, null=True, verbose_name='Passing Date')),
                ('check_number', models.CharField(blank=True, help_text='Check number from check image', max_length=50, null=True, verbose_name='Check Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='account.monthlyaccountingdocument', verbose_name='Monthly Document')),
                ('related_line_item', models.ForeignKey(blank=True, help_text='Line item that corresponds to this check (if found)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.monthlydocumentbanklineitem', verbose_name='Related Line Item')),
            ],
            options={
                'verbose_name': 'Monthly Document Check Item',
                'verbose_name_plural': 'Monthly Document Check Items',
                'db_table': 'monthly_document_check_item',
                'ordering': ['page_number', 'check_number'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyDocumentBankKeyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='Page number where this key item was found', verbose_name='Page Number')),
                ('key', models.CharField(help_text="Name of the extracted key (e.g., 'beginning_balance', 'ending_balance')", max_length=100, verbose_name='Key')),
                ('value', models.CharField(blank=True, help_text='Value associated with the key', max_length=1000, null=True, verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_items', to='account.monthlyaccountingdocument', verbose_name='Monthly Document')),
            ],
            options={
                'verbose_name': 'Monthly Document Key Item',
                'verbose_name_plural': 'Monthly Document Key Items',
                'db_table': 'monthly_document_key_item',
                'unique_together': {('document', 'page_number', 'key')},
            },
        ),
    ]
