# Generated by Django 4.2.23 on 2025-10-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_monthlydocumentattributeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyaccountingdocument',
            name='markdown_metadata',
            field=models.JSONField(blank=True, help_text='Metadata about pre-generated markdown files (page count, Azure paths, URLs)', null=True, verbose_name='Markdown Metadata'),
        ),
        migrations.AlterField(
            model_name='monthlyaccountingdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('pre_processing', 'Pre-processing'), ('pre_processed', 'Pre-processed'), ('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('classifying', 'Classifying'), ('classified', 'Classified'), ('verified', 'Verified'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Document Status'),
        ),
    ]
