# Generated by Django 4.2.23 on 2025-10-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_dimaicjetemplateheader_input_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimaicjetemplateheader',
            name='input_files',
            field=models.ManyToManyField(blank=True, help_text='The input file associated with this JE template', null=True, to='account.dimaicinputfiles', verbose_name='Input File'),
        ),
        migrations.AddField(
            model_name='factaicjetemplateheadersnapshot',
            name='input_files',
            field=models.ManyToManyField(blank=True, help_text='The input file snapshot associated with this JE template', null=True, to='account.factaicinputfilesnapshot', verbose_name='Input File Snapshot'),
        ),
    ]
