# Generated by Django 4.2.23 on 2025-11-26 11:19

import aicounting.file_upload_helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_monthlytemplatemanualattributeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydocumentbanklineitem',
            name='amount_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score (0.0-1.0) for the extracted amount from LandingAI', null=True, verbose_name='Amount Confidence Score'),
        ),
        migrations.AddField(
            model_name='monthlydocumentbanklineitem',
            name='extraction_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional extraction metadata including bounding boxes, OCR quality, etc.', null=True, verbose_name='Extraction Metadata'),
        ),
        migrations.AlterField(
            model_name='factaicinputfilesnapshot',
            name='file',
            field=models.FileField(blank=True, help_text='Snapshot copy of the input file', max_length=500, null=True, upload_to=aicounting.file_upload_helper.upload_to_monthly_accounting_snapshot_folder, verbose_name='File'),
        ),
    ]
