# Generated by Django 4.2.23 on 2025-12-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_factjetransother_doc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicjetemplateheader',
            name='input_files',
            field=models.ManyToManyField(help_text='The input file associated with this JE template', to='account.dimaicinputfiles', verbose_name='Input File'),
        ),
        migrations.AlterField(
            model_name='factaicjetemplateheadersnapshot',
            name='input_files',
            field=models.ManyToManyField(help_text='The input file snapshot associated with this JE template', to='account.factaicinputfilesnapshot', verbose_name='Input File Snapshot'),
        ),
    ]
