# Generated by Django 4.2.23 on 2025-12-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_monthlydocumentbanklineitem_modified_gl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyaccountingdocument',
            name='doc_id',
        ),
    ]
