# Generated by Django 4.2.23 on 2025-12-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_doc_id_from_monthly_accounting_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydocumentbanklineitem',
            name='is_rectified',
            field=models.BooleanField(default=False, help_text='Whether AI determined this item needs correction and provided rectified amounts', verbose_name='Is Rectified'),
        ),
        migrations.AddField(
            model_name='monthlydocumentbanklineitem',
            name='rectification_reasoning',
            field=models.TextField(blank=True, help_text='AI explanation for why rectification was suggested', null=True, verbose_name='Rectification Reasoning'),
        ),
        migrations.AddField(
            model_name='monthlydocumentbanklineitem',
            name='rectified_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score (0.0-1.0) for the rectification suggestion', null=True, verbose_name='Rectification Confidence Score'),
        ),
    ]
