# Generated by Django 4.2.23 on 2026-01-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_monthlydocumentbanklineitem_is_rectified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydocumentbanklineitem',
            name='was_missing',
            field=models.BooleanField(default=False, help_text='Whether this item was missing from Landing AI and added from Gemini extraction', verbose_name='Was Missing'),
        ),
    ]
