# Generated by Django 4.2.23 on 2026-02-04 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_monthlydocumentbanklineitem_was_compared'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, help_text='Client ID - used for grouping tasks per client', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority items are processed first')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_queue_items', to='account.monthlyaccountingdocument')),
            ],
            options={
                'verbose_name': 'Classification Queue Item',
                'verbose_name_plural': 'Classification Queue Items',
                'db_table': 'classification_queue',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['client_id', 'status', 'created_at'], name='classificat_client__ef4658_idx')],
            },
        ),
    ]
