# Generated by Django 4.2.23 on 2026-02-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_dimaicaccountant_options_and_more'),
        ('account', '0027_add_classification_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyaccountingdocument',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, help_text='Reviewer assigned via round-robin when control totals do not balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to='user.dimaicreviewer', verbose_name='Assigned Reviewer'),
        ),
        migrations.AddField(
            model_name='monthlyaccountingdocument',
            name='balance_mismatch_details',
            field=models.JSONField(blank=True, help_text='Details of the control-total balance mismatch that triggered review', null=True, verbose_name='Balance Mismatch Details'),
        ),
        migrations.AddField(
            model_name='monthlyaccountingdocument',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes left by the reviewer after reviewing the document', null=True, verbose_name='Review Notes'),
        ),
        migrations.AlterField(
            model_name='monthlyaccountingdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('pre_processing', 'Pre-processing'), ('pre_processed', 'Pre-processed'), ('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('pending_review', 'Pending Review'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('classifying', 'Classifying'), ('classified', 'Classified'), ('verified', 'Verified'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Document Status'),
        ),
    ]
