# Generated by Django 4.2.28 on 2026-02-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_monthlyaccountingdocument_assigned_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factaicmonthlyaccounting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='factaicmonthlyaccounting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted.', null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='factaicmonthlyaccounting',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag. When True, the record is considered deleted.', verbose_name='Is Deleted'),
        ),
    ]
