# Generated by Django 5.2.1 on 2025-06-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0010_alter_dimaicdocument_created_at_and_more'),
        ('user', '0003_alter_dimaicclient_city_alter_dimaicclient_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimAICAcctType',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Account Type ID')),
                ('account_type', models.CharField(max_length=255, verbose_name='Account Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AIC Account Type',
                'verbose_name_plural': 'AIC Account Types',
                'db_table': 'dim_aic_acct_type',
            },
        ),
        migrations.CreateModel(
            name='DimAICJEFreq',
            fields=[
                ('je_freq_id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Frequency ID')),
                ('je_freq', models.CharField(max_length=255, verbose_name='JE Frequency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AIC JE Frequency',
                'verbose_name_plural': 'AIC JE Frequencies',
                'db_table': 'dim_aic_je_freq',
            },
        ),
        migrations.CreateModel(
            name='DimAICJEType',
            fields=[
                ('je_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Type ID')),
                ('je_type', models.CharField(max_length=255, verbose_name='JE Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AIC JE Type',
                'verbose_name_plural': 'AIC JE Types',
                'db_table': 'dim_aic_je_type',
            },
        ),
        migrations.CreateModel(
            name='DimAICGLAcct',
            fields=[
                ('gl_acct_id', models.AutoField(primary_key=True, serialize=False, verbose_name='GL Account ID')),
                ('gl_acct_nbr', models.CharField(max_length=15, verbose_name='GL Account Number')),
                ('gl_acct_name', models.CharField(max_length=255, verbose_name='GL Account Name')),
                ('gl_acct_desc', models.TextField(verbose_name='GL Account Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('account_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dimaicaccttype', verbose_name='Account Type ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimaicclient', verbose_name='Client ID')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID')),
                ('input_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.dimaicuser')),
            ],
            options={
                'verbose_name': 'AIC GL Account',
                'verbose_name_plural': 'AIC GL Accounts',
                'db_table': 'dim_aic_gl_acct',
            },
        ),
        migrations.CreateModel(
            name='FactJETransOther',
            fields=[
                ('je_trans_id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Transaction ID')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.dimaicdocument', verbose_name='Document ID')),
                ('gl_acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dimaicglacct', verbose_name='GL Account ID')),
                ('offset_gl_acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_trans_offset_accounts', to='account.dimaicglacct', verbose_name='Offset GL Account ID')),
            ],
            options={
                'verbose_name': 'JE Transaction Other',
                'verbose_name_plural': 'JE Transactions Other',
                'db_table': 'fact_je_trans_other',
            },
        ),
    ]
