# Generated by Django 4.2.23 on 2025-08-06 04:44

import aicounting.file_upload_helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0015_rename_customer_id_dimaiccustomer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimAICAcctType',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Account Type ID')),
                ('account_type', models.CharField(max_length=255, verbose_name='Account Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AIC Account Type',
                'verbose_name_plural': 'AIC Account Types',
                'db_table': 'dim_aic_acct_type',
            },
        ),
        migrations.CreateModel(
            name='DimAICGLAcct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='GL Account ID')),
                ('account_number', models.CharField(max_length=15, verbose_name='GL Account Number')),
                ('account_name', models.CharField(max_length=255, verbose_name='GL Account Name')),
                ('description', models.TextField(verbose_name='GL Account Description')),
                ('account_class', models.CharField(help_text='e.g., Asset, Liability, Equity, Revenue, Expense', max_length=100, verbose_name='Account Class')),
                ('sub_class', models.CharField(help_text='e.g., Cash, Fixed Assets, Current Liabilities', max_length=100, verbose_name='Account Sub Class')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.dimaicaccttype', verbose_name='Account Type ID')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimaicclient', verbose_name='Client ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID')),
                ('input_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
            ],
            options={
                'verbose_name': 'AIC GL Account',
                'verbose_name_plural': 'AIC GL Accounts',
                'db_table': 'dim_aic_gl_acct',
            },
        ),
        migrations.CreateModel(
            name='DimAICJEFreq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Frequency ID')),
                ('je_freq', models.CharField(max_length=255, verbose_name='JE Frequency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AIC JE Frequency',
                'verbose_name_plural': 'AIC JE Frequencies',
                'db_table': 'dim_aic_je_freq',
            },
        ),
        migrations.CreateModel(
            name='DimAICJETemplateHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Template ID')),
                ('je_name', models.CharField(max_length=500, verbose_name='JE Name')),
                ('je_refrence', models.CharField(max_length=255, verbose_name='JE Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='user.dimaicclient', verbose_name='Client ID')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID')),
                ('je_freq', models.ForeignKey(db_column='je_freq_id', on_delete=django.db.models.deletion.CASCADE, to='account.dimaicjefreq', verbose_name='JE Frequency ID')),
            ],
            options={
                'verbose_name': 'AIC JE Template Header',
                'verbose_name_plural': 'AIC JE Template Headers',
                'db_table': 'dim_aic_je_template_header',
            },
        ),
        migrations.CreateModel(
            name='DimAICJEType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Type ID')),
                ('je_type', models.CharField(max_length=255, verbose_name='JE Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'AIC JE Type',
                'verbose_name_plural': 'AIC JE Types',
                'db_table': 'dim_aic_je_type',
            },
        ),
        migrations.CreateModel(
            name='FactJETransOther',
            fields=[
                ('je_trans_id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Transaction ID')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.dimaicdocument', verbose_name='Document ID')),
                ('gl_acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dimaicglacct', verbose_name='GL Account ID')),
                ('offset_gl_acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_trans_offset_accounts', to='account.dimaicglacct', verbose_name='Offset GL Account ID')),
            ],
            options={
                'verbose_name': 'JE Transaction Other',
                'verbose_name_plural': 'JE Transactions Other',
                'db_table': 'fact_je_trans_other',
            },
        ),
        migrations.CreateModel(
            name='FactAICJETransBank',
            fields=[
                ('je_trans_bank_id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Transaction Bank ID')),
                ('post_dt', models.DateTimeField(verbose_name='Posting Date')),
                ('trans_dt', models.DateTimeField(verbose_name='Transaction Date')),
                ('dscr', models.CharField(max_length=500, verbose_name='Description')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('class_conf_score', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Category Classification Confidence Score')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('je_trans_type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=80, verbose_name='JE Transaction Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('gl_acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_transactions', to='account.dimaicglacct', verbose_name='GL Account ID')),
                ('je_template_id', models.ForeignKey(db_column='JE_Template_Id', on_delete=django.db.models.deletion.CASCADE, to='account.dimaicjetemplateheader', verbose_name='JE Template ID')),
                ('offset_gl_acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_offset_transactions', to='account.dimaicglacct', verbose_name='Offset GL Account ID')),
            ],
            options={
                'verbose_name': 'JE Transaction Bank',
                'verbose_name_plural': 'JE Transactions Bank',
                'db_table': 'fact_je_trans_bank',
            },
        ),
        migrations.CreateModel(
            name='FactAICJEMonthlyStat',
            fields=[
                ('je_trans_id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Transaction ID')),
                ('je_mth', models.IntegerField(verbose_name='JE Month')),
                ('je_yr', models.IntegerField(verbose_name='JE Year')),
                ('is_processed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('je_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dimaicjetemplateheader', verbose_name='JE Template ID')),
            ],
            options={
                'verbose_name': 'AIC JE Transaction',
                'verbose_name_plural': 'AIC JE Transactions',
                'db_table': 'fact_aic_je_monthly_stat',
            },
        ),
        migrations.CreateModel(
            name='DimAICTemplateDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_comments', models.TextField(verbose_name='Document Comments')),
                ('doc_ai_prompt', models.TextField(verbose_name='Document AI Prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.dimaicdocument', verbose_name='Document ID')),
                ('je_template_gl_acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dimaicglacct', verbose_name='JE Temaplate GL Account ID')),
            ],
            options={
                'verbose_name': 'AIC Template Document',
                'verbose_name_plural': 'AIC Template Documents',
                'db_table': 'dim_aic_template_doc',
            },
        ),
        migrations.AddField(
            model_name='dimaicjetemplateheader',
            name='je_type',
            field=models.ForeignKey(blank=True, db_column='je_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dimaicjetype', verbose_name='JE Type ID'),
        ),
        migrations.CreateModel(
            name='DimAICJETemplateGL',
            fields=[
                ('je_template_gl_id', models.AutoField(primary_key=True, serialize=False, verbose_name='GL Account Type ID')),
                ('acct_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dimaicaccttype', verbose_name='GL Account Type ID')),
                ('gl_acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dimaicglacct', verbose_name='GL Account ID')),
                ('je_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.dimaicjetemplateheader', verbose_name='JE Template ID')),
                ('offset_gl_acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_gl_templates', to='account.dimaicglacct', verbose_name='Offset GL Account ID')),
            ],
            options={
                'verbose_name': 'AIC JE Template GL',
                'verbose_name_plural': 'AIC JE Template GLs',
                'db_table': 'dim_aic_je_template_gl',
            },
        ),
        migrations.CreateModel(
            name='DimAicInputFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Input File ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('file_type', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('credit_card', 'Credit Card'), ('sales', 'Sales')], help_text='Type of the input file', max_length=20, verbose_name='File Type')),
                ('file', models.FileField(help_text='Upload the input file', upload_to=aicounting.file_upload_helper.upload_to_input_files_folder, verbose_name='File')),
                ('description', models.TextField(blank=True, help_text='Additional description or comments about the input file', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='user.dimaicclient', verbose_name='Client')),
                ('input_user', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
            ],
            options={
                'verbose_name': 'Input File',
                'verbose_name_plural': 'Input Files',
                'db_table': 'dim_aic_input_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DimAicInputFileAttributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Attribute ID')),
                ('name', models.CharField(help_text='Name of the attribute', max_length=255, verbose_name='Attribute Name')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], help_text='Credit or Debit type', max_length=10, verbose_name='Type')),
                ('comments', models.TextField(blank=True, help_text='Additional comments or notes', null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_file_attributes', to='account.dimaicglacct', verbose_name='GL Account')),
                ('input_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='account.dimaicinputfiles', verbose_name='Input File')),
                ('input_user', models.ForeignKey(help_text='User who created this attribute', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
                ('offset_gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_input_file_attributes', to='account.dimaicglacct', verbose_name='Offset GL Account')),
            ],
            options={
                'verbose_name': 'Input File Attribute',
                'verbose_name_plural': 'Input File Attributes',
                'db_table': 'dim_aic_input_file_attributes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dimaicjetemplateheader',
            unique_together={('customer', 'client', 'je_freq', 'je_name')},
        ),
        migrations.CreateModel(
            name='DimAICJETemplateAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Template Attribute ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('input_file_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_templates', to='account.dimaicinputfileattributes', verbose_name='Input File Attribute')),
                ('input_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
                ('je_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_attributes', to='account.dimaicjetemplateheader', verbose_name='JE Template ID')),
            ],
            options={
                'verbose_name': 'AIC JE Template Attribute',
                'verbose_name_plural': 'AIC JE Template Attributes',
                'db_table': 'dim_aic_je_template_attribute',
                'unique_together': {('je_template_id', 'input_file_attribute')},
            },
        ),
    ]
