# Generated by Django 4.2.23 on 2025-07-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimaicglacct',
            name='account_class',
            field=models.CharField(default=1, help_text='e.g., Asset, Liability, Equity, Revenue, Expense', max_length=100, verbose_name='Account Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimaicglacct',
            name='sub_class',
            field=models.CharField(default=1, help_text='e.g., Cash, Fixed Assets, Current Liabilities', max_length=100, verbose_name='Account Sub Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimaicglacct',
            name='account_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.dimaicaccttype', verbose_name='Account Type ID'),
        ),
    ]
