# Generated by Django 4.2.23 on 2025-07-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_dimaicglacct_account_class_dimaicglacct_sub_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimaicglacct',
            old_name='gl_acct_name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='dimaicglacct',
            old_name='gl_acct_nbr',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='dimaicglacct',
            old_name='account_type_id',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='dimaicglacct',
            old_name='cust_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='dimaicglacct',
            old_name='gl_acct_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dimaicglacct',
            old_name='gl_acct_id',
            new_name='id',
        ),
    ]
