# Generated by Django 4.2.23 on 2025-08-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_make_offset_gl_account_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dimaicjetemplateattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dimaicjetemplateattribute',
            name='attribute_name',
            field=models.CharField(blank=True, help_text='Name of the attribute when referenced by ID', max_length=255, null=True, verbose_name='Attribute Name'),
        ),
        migrations.AddField(
            model_name='dimaicjetemplateattribute',
            name='credit',
            field=models.CharField(blank=True, help_text="Credit value: can be null, number as string, attribute_id, or 'manual'", max_length=255, null=True, verbose_name='Credit'),
        ),
        migrations.AddField(
            model_name='dimaicjetemplateattribute',
            name='debit',
            field=models.CharField(blank=True, help_text="Debit value: can be null, number as string, attribute_id, or 'manual'", max_length=255, null=True, verbose_name='Debit'),
        ),
        migrations.AddField(
            model_name='dimaicjetemplateattribute',
            name='gl_account',
            field=models.ForeignKey(blank=True, help_text='For non-object templates - the GL account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='je_template_attributes', to='account.dimaicglacct', verbose_name='GL Account'),
        ),
        migrations.AddField(
            model_name='dimaicjetemplateheader',
            name='input_file',
            field=models.ForeignKey(blank=True, db_column='input_file_id', help_text='The input file associated with this JE template', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.dimaicinputfiles', verbose_name='Input File'),
        ),
        migrations.AddField(
            model_name='dimaicjetemplateheader',
            name='is_object',
            field=models.BooleanField(default=False, help_text='Indicates if the template is an object template or not', verbose_name='Is Object'),
        ),
        migrations.AlterField(
            model_name='dimaicjetemplateattribute',
            name='input_file_attribute',
            field=models.ForeignKey(blank=True, help_text='For object templates - the attribute from input file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='je_templates', to='account.dimaicinputfileattributes', verbose_name='Input File Attribute'),
        ),
    ]
