# Generated by Django 5.2.1 on 2025-06-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_dimaicjetemplateheader_dimaicjetemplategl_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dimaicjetemplateheader',
            table='dim_aic_je_template_header',
        ),
    ]
