# Generated by Django 4.2.23 on 2025-08-01 16:07

import aicounting.model_file_upload_helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_customer_id_dimaiccustomer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_rename_gl_acct_name_dimaicglacct_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimAicInputFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Input File ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('file_type', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('credit_card', 'Credit Card'), ('sales', 'Sales')], help_text='Type of the input file', max_length=20, verbose_name='File Type')),
                ('file', models.FileField(help_text='Upload the input file', upload_to=aicounting.model_file_upload_helper.upload_to_input_files_folder, verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='user.dimaicclient', verbose_name='Client')),
                ('input_user', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
            ],
            options={
                'verbose_name': 'Input File',
                'verbose_name_plural': 'Input Files',
                'db_table': 'dim_aic_input_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DimAicInputFileAttributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Attribute ID')),
                ('name', models.CharField(help_text='Name of the attribute', max_length=255, verbose_name='Attribute Name')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], help_text='Credit or Debit type', max_length=10, verbose_name='Type')),
                ('comments', models.TextField(blank=True, help_text='Additional comments or notes', null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_file_attributes', to='account.dimaicglacct', verbose_name='GL Account')),
                ('input_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='account.dimaicinputfiles', verbose_name='Input File')),
                ('input_user', models.ForeignKey(help_text='User who created this attribute', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
                ('offset_gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offset_input_file_attributes', to='account.dimaicglacct', verbose_name='Offset GL Account')),
            ],
            options={
                'verbose_name': 'Input File Attribute',
                'verbose_name_plural': 'Input File Attributes',
                'db_table': 'dim_aic_input_file_attributes',
                'ordering': ['-created_at'],
            },
        ),
    ]
