# Generated by Django 4.2.23 on 2025-08-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_dimaicinputfiles_dimaicinputfileattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimaicinputfiles',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description or comments about the input file', null=True, verbose_name='Description'),
        ),
    ]
