# Generated by Django 4.2.23 on 2025-08-03 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_customer_id_dimaiccustomer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_dimaicinputfiles_dimaicinputfileattributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimaicjefreq',
            old_name='je_freq_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dimaicjetemplateheader',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='dimaicjetemplateheader',
            old_name='cust_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='dimaicjetemplateheader',
            old_name='je_template_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='dimaicjetemplateheader',
            old_name='je_freq_id',
            new_name='je_freq',
        ),
        migrations.RenameField(
            model_name='dimaicjetemplateheader',
            old_name='je_ref',
            new_name='je_refrence',
        ),
        migrations.RenameField(
            model_name='dimaicjetype',
            old_name='je_type_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='dimaicjetemplateheader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimaicjetemplateheader',
            name='je_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dimaicjetype', verbose_name='JE Type ID'),
        ),
        migrations.AddField(
            model_name='dimaicjetemplateheader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='factaicjetransbank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factaicjetransbank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterUniqueTogether(
            name='dimaicjetemplateheader',
            unique_together={('customer', 'client', 'je_freq', 'je_name')},
        ),
        migrations.RemoveField(
            model_name='dimaicjetemplateheader',
            name='je_type_id',
        ),
        migrations.CreateModel(
            name='DimAICJETemplateAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Template Attribute ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('input_file_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_templates', to='account.dimaicinputfileattributes', verbose_name='Input File Attribute')),
                ('input_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
                ('je_template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_attributes', to='account.dimaicjetemplateheader', verbose_name='JE Template ID')),
            ],
            options={
                'verbose_name': 'AIC JE Template Attribute',
                'verbose_name_plural': 'AIC JE Template Attributes',
                'db_table': 'dim_aic_je_template_attribute',
                'unique_together': {('je_template_id', 'input_file_attribute')},
            },
        ),
    ]
