# Generated by Django 4.2.23 on 2025-08-10 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0015_rename_customer_id_dimaiccustomer_id'),
        ('account', '0004_dimaicjetemplateheader_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactAICInputFileAttributeSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Attribute Snapshot ID')),
                ('name', models.CharField(help_text='Name of the attribute', max_length=255, verbose_name='Attribute Name')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], help_text='Credit or Debit type', max_length=10, verbose_name='Type')),
                ('comments', models.TextField(blank=True, help_text='Additional comments or notes', null=True, verbose_name='Comments')),
                ('original_created_at', models.DateTimeField(verbose_name='Original Created At')),
                ('original_updated_at', models.DateTimeField(verbose_name='Original Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Snapshot Created At')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_file_attribute_snapshots', to='account.dimaicglacct', verbose_name='GL Account')),
            ],
            options={
                'verbose_name': 'Input File Attribute Snapshot',
                'verbose_name_plural': 'Input File Attribute Snapshots',
                'db_table': 'fact_aic_input_file_attribute_snapshot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactAICInputFileSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Input File Snapshot ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file_type', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('credit_card', 'Credit Card'), ('sales', 'Sales')], help_text='Type of the input file', max_length=20, verbose_name='File Type')),
                ('file', models.CharField(help_text='Path to the input file at time of snapshot', max_length=500, verbose_name='File Path')),
                ('description', models.TextField(blank=True, help_text='Additional description or comments about the input file', null=True, verbose_name='Description')),
                ('original_created_at', models.DateTimeField(verbose_name='Original Created At')),
                ('original_updated_at', models.DateTimeField(verbose_name='Original Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Snapshot Created At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_file_snapshots', to='user.dimaicclient', verbose_name='Client')),
                ('input_user', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
            ],
            options={
                'verbose_name': 'Input File Snapshot',
                'verbose_name_plural': 'Input File Snapshots',
                'db_table': 'fact_aic_input_file_snapshot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactAICMonthlyAccounting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Monthly Accounting ID')),
                ('month', models.IntegerField(help_text='Month (1-12)', verbose_name='Month')),
                ('year', models.IntegerField(help_text='Year (e.g., 2025)', verbose_name='Year')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_accounting', to='user.dimaicclient', verbose_name='Client')),
                ('created_by', models.ForeignKey(help_text='User who initiated this accounting session', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Monthly Accounting',
                'verbose_name_plural': 'Monthly Accounting Sessions',
                'db_table': 'fact_aic_monthly_accounting',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='FactAICJETemplateHeaderSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Template Snapshot ID')),
                ('je_name', models.CharField(max_length=500, verbose_name='JE Name')),
                ('je_refrence', models.CharField(max_length=255, verbose_name='JE Reference')),
                ('is_object', models.BooleanField(default=False, help_text='Indicates if the template is an object template or not', verbose_name='Is Object')),
                ('description', models.TextField(blank=True, help_text='Additional description or comments about the Template', null=True, verbose_name='Description')),
                ('original_created_at', models.DateTimeField(verbose_name='Original Created At')),
                ('original_updated_at', models.DateTimeField(verbose_name='Original Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Snapshot Created At')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='user.dimaicclient', verbose_name='Client ID')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='user.dimaiccustomer', verbose_name='Customer ID')),
                ('input_file', models.ForeignKey(blank=True, db_column='input_file_id', help_text='The input file snapshot associated with this JE template', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.factaicinputfilesnapshot', verbose_name='Input File Snapshot')),
                ('je_freq', models.ForeignKey(db_column='je_freq_id', on_delete=django.db.models.deletion.CASCADE, to='account.dimaicjefreq', verbose_name='JE Frequency ID')),
                ('je_type', models.ForeignKey(blank=True, db_column='je_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dimaicjetype', verbose_name='JE Type ID')),
                ('monthly_accounting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_template_snapshots', to='account.factaicmonthlyaccounting', verbose_name='Monthly Accounting')),
                ('original_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dimaicjetemplateheader', verbose_name='Original Template')),
            ],
            options={
                'verbose_name': 'JE Template Header Snapshot',
                'verbose_name_plural': 'JE Template Header Snapshots',
                'db_table': 'fact_aic_je_template_header_snapshot',
            },
        ),
        migrations.CreateModel(
            name='FactAICJETemplateAttributeSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='JE Template Attribute Snapshot ID')),
                ('debit', models.CharField(blank=True, help_text="Debit value: can be null, number as string, attribute_id, or 'manual'", max_length=255, null=True, verbose_name='Debit')),
                ('credit', models.CharField(blank=True, help_text="Credit value: can be null, number as string, attribute_id, or 'manual'", max_length=255, null=True, verbose_name='Credit')),
                ('attribute_name', models.CharField(blank=True, help_text='Name of the attribute when referenced by ID', max_length=255, null=True, verbose_name='Attribute Name')),
                ('original_created_at', models.DateTimeField(verbose_name='Original Created At')),
                ('original_updated_at', models.DateTimeField(verbose_name='Original Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Snapshot Created At')),
                ('gl_account', models.ForeignKey(blank=True, help_text='For non-object templates - the GL account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='je_template_attribute_snapshots', to='account.dimaicglacct', verbose_name='GL Account')),
                ('input_file_attribute', models.ForeignKey(blank=True, help_text='For object templates - the attribute snapshot from input file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='je_template_snapshots', to='account.factaicinputfileattributesnapshot', verbose_name='Input File Attribute Snapshot')),
                ('input_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
                ('je_template_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_snapshots', to='account.factaicjetemplateheadersnapshot', verbose_name='JE Template Snapshot')),
                ('original_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dimaicjetemplateattribute', verbose_name='Original Template Attribute')),
            ],
            options={
                'verbose_name': 'JE Template Attribute Snapshot',
                'verbose_name_plural': 'JE Template Attribute Snapshots',
                'db_table': 'fact_aic_je_template_attribute_snapshot',
            },
        ),
        migrations.AddField(
            model_name='factaicinputfilesnapshot',
            name='monthly_accounting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_file_snapshots', to='account.factaicmonthlyaccounting', verbose_name='Monthly Accounting'),
        ),
        migrations.AddField(
            model_name='factaicinputfilesnapshot',
            name='original_input_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dimaicinputfiles', verbose_name='Original Input File'),
        ),
        migrations.AddField(
            model_name='factaicinputfileattributesnapshot',
            name='input_file_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_snapshots', to='account.factaicinputfilesnapshot', verbose_name='Input File Snapshot'),
        ),
        migrations.AddField(
            model_name='factaicinputfileattributesnapshot',
            name='input_user',
            field=models.ForeignKey(help_text='User who created this attribute', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Input User'),
        ),
        migrations.AddField(
            model_name='factaicinputfileattributesnapshot',
            name='offset_gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offset_input_file_attribute_snapshots', to='account.dimaicglacct', verbose_name='Offset GL Account'),
        ),
        migrations.AddField(
            model_name='factaicinputfileattributesnapshot',
            name='original_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.dimaicinputfileattributes', verbose_name='Original Attribute'),
        ),
    ]
