# Generated by Django 4.2.23 on 2025-08-12 14:55

import aicounting.file_upload_helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_factaicinputfileattributesnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAccountingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this document', unique=True, verbose_name='Document UUID')),
                ('doc_type', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('credit_card', 'Credit Card'), ('sales', 'Sales')], help_text='Type of document (same as input file type)', max_length=20, verbose_name='Document Type')),
                ('upload_status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Upload Status')),
                ('file', models.FileField(blank=True, help_text='The file uploaded by the user for extraction', null=True, upload_to=aicounting.file_upload_helper.upload_to_montly_accounting_folder, verbose_name='Uploaded File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Monthly Accounting Document',
                'verbose_name_plural': 'Monthly Accounting Documents',
                'db_table': 'monthly_accounting_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='factaicinputfilesnapshot',
            name='file',
            field=models.FileField(blank=True, help_text='Snapshot copy of the input file', null=True, upload_to='monthly_accounting_snapshots/', verbose_name='File'),
        ),
        migrations.DeleteModel(
            name='FactAICDocumentForExtraction',
        ),
        migrations.AddField(
            model_name='monthlyaccountingdocument',
            name='input_file_snapshot',
            field=models.ForeignKey(help_text='Reference to the input file snapshot this document is based on', on_delete=django.db.models.deletion.CASCADE, related_name='extraction_documents', to='account.factaicinputfilesnapshot', verbose_name='Input File Snapshot'),
        ),
        migrations.AddField(
            model_name='monthlyaccountingdocument',
            name='monthly_accounting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='account.factaicmonthlyaccounting', verbose_name='Monthly Accounting Session'),
        ),
        migrations.AddField(
            model_name='monthlyaccountingdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyaccountingdocument',
            unique_together={('monthly_accounting', 'input_file_snapshot')},
        ),
    ]
