# Generated by Django 4.2.23 on 2025-09-10 14:54

import aicounting.model_file_upload_helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_monthlyaccountingdocument_control_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyaccountingdocument',
            name='upload_status',
        ),
        migrations.AddField(
            model_name='factaicjetemplateheadersnapshot',
            name='je_export_file',
            field=models.FileField(blank=True, help_text='Exported JE template file (e.g., CSV)', null=True, upload_to=aicounting.model_file_upload_helper.upload_to_je_export_folder, verbose_name='JE Export File'),
        ),
        migrations.AddField(
            model_name='monthlyaccountingdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('classifying', 'Classifying'), ('classified', 'Classified'), ('verified', 'Verified'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Document Status'),
        ),
    ]
