# Generated by Django 4.2.23 on 2025-09-20 08:59

import aicounting.model_file_upload_helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_monthlyaccountingdocument_upload_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicinputfiles',
            name='file',
            field=models.FileField(help_text='Upload the input file', max_length=500, upload_to=aicounting.model_file_upload_helper.upload_to_input_files_folder, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='factaicinputfilesnapshot',
            name='file',
            field=models.FileField(blank=True, help_text='Snapshot copy of the input file', max_length=500, null=True, upload_to='monthly_accounting_snapshots/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='factaicjetemplateheadersnapshot',
            name='je_export_file',
            field=models.FileField(blank=True, help_text='Exported JE template file (e.g., CSV)', max_length=500, null=True, upload_to=aicounting.model_file_upload_helper.upload_to_je_export_folder, verbose_name='JE Export File'),
        ),
        migrations.AlterField(
            model_name='monthlyaccountingdocument',
            name='file',
            field=models.FileField(blank=True, help_text='The file uploaded by the user for extraction', max_length=500, null=True, upload_to=aicounting.model_file_upload_helper.upload_to_montly_accounting_folder, verbose_name='Uploaded File'),
        ),
    ]
