# Generated by Django 4.2.23 on 2025-09-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_dimaicinputfiles_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyDocumentAttributeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='Page number where this attribute item was found', verbose_name='Page Number')),
                ('value', models.CharField(blank=True, help_text='Value associated with the attribute', max_length=1000, null=True, verbose_name='Attribute Value')),
                ('transaction_type', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='Whether this is a debit or credit transaction', max_length=10, null=True, verbose_name='Transaction Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_document_attributes', to='account.factaicinputfileattributesnapshot', verbose_name='Input File Attribute')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_items', to='account.monthlyaccountingdocument', verbose_name='Monthly Document')),
                ('gl_account', models.ForeignKey(blank=True, help_text='GL account assigned through classification pipeline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_document_attribute_items', to='account.dimaicglacct', verbose_name='GL Account')),
                ('offset_gl_account', models.ForeignKey(blank=True, help_text='Offset GL account for double-entry booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_document_offset_attribute_items', to='account.dimaicglacct', verbose_name='Offset GL Account')),
            ],
            options={
                'verbose_name': 'Monthly Document Attribute Item',
                'verbose_name_plural': 'Monthly Document Attribute Items',
                'db_table': 'monthly_document_attribute_item',
                'unique_together': {('document', 'attribute', 'page_number')},
            },
        ),
    ]
