# Generated by Django 4.2.23 on 2025-10-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_add_markdown_preprocessing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimaicjetemplateheader',
            name='input_file',
        ),
        migrations.RemoveField(
            model_name='factaicjetemplateheadersnapshot',
            name='input_file',
        )
    ]
