# Generated by Django 4.2.23 on 2025-10-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_add_input_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicinputfileattributes',
            name='input_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='account.dimaicinputfiles', verbose_name='Input File'),
        ),
    ]
