# Generated by Django 4.2.23 on 2025-10-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_dimaicinputfileattributes_input_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='factaicjetemplateheadersnapshot',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20, null=True, verbose_name='JE Template Status'),
        ),
    ]
