# Generated by Django 4.2.23 on 2025-10-22 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0016_factaicjetemplateheadersnapshot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTemplateManualAttributeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='Manual value entered for this attribute', max_length=1000, null=True, verbose_name='Attribute Value')),
                ('transaction_type', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='Whether this is a debit or credit transaction', max_length=10, null=True, verbose_name='Transaction Type')),
                ('description', models.TextField(blank=True, help_text='Description or notes for this manual entry', null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('entered_by', models.ForeignKey(blank=True, help_text='User who entered this manual value', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Entered By')),
                ('gl_account', models.ForeignKey(blank=True, help_text='GL account for this manual entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_template_manual_attribute_items', to='account.dimaicglacct', verbose_name='GL Account')),
                ('offset_gl_account', models.ForeignKey(blank=True, help_text='Offset GL account for double-entry booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_template_offset_manual_attribute_items', to='account.dimaicglacct', verbose_name='Offset GL Account')),
                ('template_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_attribute_items', to='account.factaicjetemplateattributesnapshot', verbose_name='JE Template Attribute')),
            ],
            options={
                'verbose_name': 'Monthly Template Manual Attribute Item',
                'verbose_name_plural': 'Monthly Template Manual Attribute Items',
                'db_table': 'monthly_template_manual_attribute_item',
                'ordering': ['-created_at'],
            },
        ),
    ]
