# Generated by Django 4.2.23 on 2025-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_add_confidence_and_metadata_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicinputfiles',
            name='file_type',
            field=models.CharField(choices=[('bank_statement', 'Bank Statement'), ('credit_card', 'Credit Card'), ('sales', 'Sales'), ('payroll', 'Payroll'), ('misc', 'Misc')], help_text='Type of the input file', max_length=20, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='factaicinputfilesnapshot',
            name='file_type',
            field=models.CharField(choices=[('bank_statement', 'Bank Statement'), ('credit_card', 'Credit Card'), ('sales', 'Sales'), ('payroll', 'Payroll'), ('misc', 'Misc')], help_text='Type of the input file', max_length=20, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='monthlyaccountingdocument',
            name='doc_type',
            field=models.CharField(choices=[('bank_statement', 'Bank Statement'), ('credit_card', 'Credit Card'), ('sales', 'Sales'), ('payroll', 'Payroll'), ('misc', 'Misc')], help_text='Type of document (same as input file type)', max_length=20, verbose_name='Document Type'),
        ),
    ]
