# Generated by Django 4.2.23 on 2025-12-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_dimaicinputfiles_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factjetransother',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='factjetransother',
            name='gl_acct_id',
        ),
        migrations.RemoveField(
            model_name='factjetransother',
            name='offset_gl_acct_id',
        ),
        migrations.DeleteModel(
            name='DimAICTemplateDoc',
        ),
        migrations.DeleteModel(
            name='FactJETransOther',
        ),
    ]
