# Generated by Django 4.2.23 on 2025-12-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_dimaicjetemplateheader_input_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydocumentbanklineitem',
            name='modified_gl',
            field=models.BooleanField(default=False, help_text='Whether the GL account was manually modified after classification', verbose_name='Modified GL'),
        ),
    ]
