# Generated by Django 4.2.23 on 2026-02-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_monthlydocumentbanklineitem_was_missing'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydocumentbanklineitem',
            name='was_compared',
            field=models.BooleanField(default=False, help_text='Whether no suitable rectifier was found for this line item', verbose_name='No Rectifier Match'),
        ),
    ]
