# Generated by Django 5.2.1 on 2026-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_platform_staff',
            field=models.BooleanField(default=False, help_text="Operates the platform itself, not any one firm — belongs to no FirmMembership and sees the cross-firm /platform/ surface instead of a firm's own dashboard."),
        ),
    ]
