# Generated by Django 5.2.1 on 2025-06-25 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimAICDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(default=uuid.uuid4, max_length=72, verbose_name='UUID')),
                ('doc_typ', models.CharField(max_length=50, verbose_name='Document Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('file_format', models.CharField(max_length=8, verbose_name='File Format')),
                ('upload_stat', models.CharField(max_length=25, verbose_name='Upload Status')),
                ('input_user', models.IntegerField(verbose_name='Input User')),
                ('file_loc', models.CharField(max_length=1000, verbose_name='File Location')),
                ('control_item', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AIC Document',
                'verbose_name_plural': 'AIC Documents',
                'db_table': 'dim_aic_doc',
            },
        ),
        migrations.CreateModel(
            name='FactAICDocKeyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(verbose_name='Line Number')),
                ('page_number', models.IntegerField(verbose_name='Page Number')),
                ('key', models.CharField(max_length=100, verbose_name='Key')),
                ('value', models.CharField(max_length=1000, null=True, verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_items', to='document.dimaicdocument')),
            ],
            options={
                'verbose_name': 'AIC Document Key Item',
                'verbose_name_plural': 'AIC Document Key Items',
                'db_table': 'fact_aic_doc_key_item',
            },
        ),
        migrations.CreateModel(
            name='FactAICDocLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(verbose_name='Page Number')),
                ('line_number', models.IntegerField(verbose_name='Line Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_rows', to='document.dimaicdocument')),
            ],
            options={
                'verbose_name': 'AIC Document Line Row',
                'verbose_name_plural': 'AIC Document Line Rows',
                'db_table': 'fact_aic_doc_line',
            },
        ),
        migrations.CreateModel(
            name='FactAICDocLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Column Name')),
                ('value', models.TextField(null=True, verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='document.factaicdocline')),
            ],
            options={
                'verbose_name': 'AIC Document Line Item Value',
                'verbose_name_plural': 'AIC Document Line Item Values',
                'db_table': 'fact_aic_doc_line_value',
            },
        ),
    ]
