# Generated by Django 4.2.23 on 2025-07-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactAICDocCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100, verbose_name='Amount')),
                ('payee', models.TextField(blank=True, null=True, verbose_name='Payee')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='Memo')),
                ('clearing_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clearing Date')),
                ('passing_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Passing Date')),
                ('check_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Check Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='document.dimaicdocument')),
            ],
            options={
                'verbose_name': 'AIC Document Check Item',
                'verbose_name_plural': 'AIC Document Check Items',
                'db_table': 'fact_aic_doc_check_items',
            },
        ),
    ]
