# Generated by Django 5.2.1 on 2025-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factaicdoclineitem',
            name='page_number',
        ),
        migrations.AddField(
            model_name='factaicdockeyitem',
            name='line_number',
            field=models.IntegerField(default=0, help_text='Page number where the key-value was extracted from', verbose_name='Line Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factaicdocline',
            name='page_number',
            field=models.IntegerField(default=0, help_text='Page number where this line item appears', verbose_name='Page Number'),
            preserve_default=False,
        ),
    ]
