# Generated by Django 4.2.23 on 2025-07-30 13:19

from django.db import migrations, models
import document.models.dim_aic_doc_model


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_factaicdoccheckitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimaicdocument',
            name='file_loc',
        ),
        migrations.AddField(
            model_name='dimaicdocument',
            name='file',
            field=models.FileField(default=1, help_text='File stored in Azure Blob Storage', max_length=500, upload_to=document.models.dim_aic_doc_model.upload_to_documents_folder, verbose_name='Document File'),
            preserve_default=False,
        ),
    ]
