# Generated by Django 5.2.1 on 2025-06-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_factaicdoclineitem_page_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factaicdockeyitem',
            name='line_number',
            field=models.IntegerField(help_text='Line number where the key-value was extracted from', verbose_name='Line Number'),
        ),
    ]
