# Generated by Django 5.2.1 on 2025-06-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_factaicdockeyitem_line_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factaicdockeyitem',
            name='value',
            field=models.CharField(help_text='Value corresponding to the extracted key', max_length=1000, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='factaicdoclineitem',
            name='value',
            field=models.TextField(null=True, verbose_name='Value'),
        ),
    ]
