# Generated by Django 5.2.1 on 2025-06-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_factaicdockeyitem_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimaicdocument',
            name='control_item',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
