# Generated by Django 5.2.1 on 2025-06-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_dimaicdocument_control_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicdocument',
            name='control_item',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
