# Generated by Django 5.2.1 on 2025-06-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_dimaicdocument_control_item'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dimaicdocument',
            table='dim_ai_doc',
        ),
    ]
