# Generated by Django 5.2.1 on 2025-06-23 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_alter_dimaicdocument_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicdocument',
            name='doc_id',
            field=models.CharField(default=uuid.uuid4, help_text='Unique identifier for each document', max_length=72, verbose_name='UUID'),
        ),
    ]
