# Generated by Django 5.2.1 on 2025-06-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_dimaicdocument_doc_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dimaicdocument',
            table='dim_aic_doc',
        ),
    ]
