# Generated by Django 5.2.1 on 2025-06-23 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_alter_dimaicdocument_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimaicdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='dimaicdocument',
            name='doc_id',
            field=models.CharField(default=uuid.uuid4, max_length=72, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='dimaicdocument',
            name='doc_typ',
            field=models.CharField(max_length=50, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='dimaicdocument',
            name='file_format',
            field=models.CharField(max_length=8, verbose_name='File Format'),
        ),
        migrations.AlterField(
            model_name='dimaicdocument',
            name='file_loc',
            field=models.CharField(max_length=1000, verbose_name='File Location'),
        ),
        migrations.AlterField(
            model_name='dimaicdocument',
            name='input_user',
            field=models.IntegerField(verbose_name='Input User'),
        ),
        migrations.AlterField(
            model_name='dimaicdocument',
            name='upload_stat',
            field=models.CharField(max_length=25, verbose_name='Upload Status'),
        ),
        migrations.AlterField(
            model_name='factaicdockeyitem',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='factaicdockeyitem',
            name='line_number',
            field=models.IntegerField(verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='factaicdockeyitem',
            name='page_number',
            field=models.IntegerField(verbose_name='Page Number'),
        ),
        migrations.AlterField(
            model_name='factaicdockeyitem',
            name='value',
            field=models.CharField(max_length=1000, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='factaicdocline',
            name='line_number',
            field=models.IntegerField(verbose_name='Line Number'),
        ),
        migrations.AlterField(
            model_name='factaicdocline',
            name='page_number',
            field=models.IntegerField(verbose_name='Page Number'),
        ),
    ]
