# Generated by Django 5.2.1 on 2026-09-03 12:34

import django.db.models.deletion
import storage.uploads
import v1.common.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('external_ref', models.CharField(help_text="The firm's own code for this client. Unique per firm, not globally.", max_length=64)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('allow_review', models.BooleanField(default=False, help_text='Route documents to a human reviewer when control totals do not balance')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('public_id', models.CharField(editable=False, help_text='Human-quotable firm reference, e.g. 1234-5678', max_length=9, unique=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Firm',
                'verbose_name_plural': 'Firms',
                'db_table': 'firm',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tenancy.client')),
            ],
            options={
                'verbose_name': 'Client Contact',
                'verbose_name_plural': 'Client Contacts',
                'db_table': 'client_contact',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='tenancy.firm'),
        ),
        migrations.CreateModel(
            name='FirmMembership',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('accountant', 'Accountant'), ('reviewer', 'Reviewer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('review_assigned_at', models.DateTimeField(blank=True, help_text='Last time this reviewer was handed a document; drives round-robin', null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.firm')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firm Membership',
                'verbose_name_plural': 'Firm Memberships',
                'db_table': 'firm_membership',
            },
        ),
        migrations.CreateModel(
            name='ClientAssignment',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tenancy.client')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='tenancy.firmmembership')),
            ],
            options={
                'verbose_name': 'Client Assignment',
                'verbose_name_plural': 'Client Assignments',
                'db_table': 'client_assignment',
            },
        ),
        migrations.CreateModel(
            name='ClientReferenceDocument',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('chart_of_accounts', 'Chart of Accounts'), ('vendor_list', 'Vendor List'), ('gl_history', 'GL History')], max_length=32)),
                ('file', models.FileField(max_length=500, upload_to=storage.uploads.upload_to_customer_client_folder)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_documents', to='tenancy.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reference_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Reference Document',
                'verbose_name_plural': 'Client Reference Documents',
                'db_table': 'client_reference_document',
                'indexes': [models.Index(fields=['client', 'kind'], name='client_refe_client__669857_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['firm', 'is_deleted'], name='client_firm_id_3cbad5_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('firm', 'external_ref'), name='uniq_client_ref_per_firm'),
        ),
        migrations.AddIndex(
            model_name='firmmembership',
            index=models.Index(fields=['user', 'is_active'], name='firm_member_user_id_40e1bb_idx'),
        ),
        migrations.AddIndex(
            model_name='firmmembership',
            index=models.Index(fields=['firm', 'role', 'is_active'], name='firm_member_firm_id_bad6e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='firmmembership',
            constraint=models.UniqueConstraint(fields=('user', 'firm', 'role'), name='uniq_membership_user_firm_role'),
        ),
        migrations.AddConstraint(
            model_name='clientassignment',
            constraint=models.UniqueConstraint(fields=('client', 'membership'), name='uniq_client_membership'),
        ),
    ]
