# Generated by Django 5.2.1 on 2026-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='extraction_provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('claude', 'Claude')], default='gemini', help_text="Which LLM reads this firm's bank/credit-card statements. A lever for outage response — flip it here rather than waiting on a deploy. Field-configured documents (payroll, sales, ...) go through LandingAI regardless; there is only one provider for those today.", max_length=16),
        ),
    ]
