# Generated by Django 5.2.1 on 2026-09-04 07:48

import django.db.models.deletion
import storage.uploads
import v1.common.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('ledger', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='tenancy.client')),
                ('config_version', models.ForeignKey(help_text='The configuration this period was opened against; never changes', on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='configuration.configversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Period',
                'verbose_name_plural': 'Accounting Periods',
                'db_table': 'accounting_period',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PeriodDocument',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_key', models.CharField(help_text="Stable key into the period's frozen config payload", max_length=128)),
                ('source_name', models.CharField(help_text='Source name as it stood when the period opened', max_length=255)),
                ('category_key', models.CharField(help_text="The document category's key when this period was opened", max_length=64)),
                ('category_label', models.CharField(max_length=255)),
                ('extraction_mode', models.CharField(help_text="'transactional' or 'fields' — which pipeline this document runs through", max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('pending_review', 'Pending Review'), ('in_review', 'In Review'), ('reviewed', 'Reviewed'), ('classifying', 'Classifying'), ('classified', 'Classified'), ('verified', 'Verified'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to=storage.uploads.upload_to_montly_accounting_folder)),
                ('failure_reason', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('balance_mismatch_details', models.JSONField(blank=True, null=True)),
                ('control_totals', models.JSONField(blank=True, help_text='Opening/closing balances and totals extracted from the document', null=True)),
                ('markdown_metadata', models.JSONField(blank=True, help_text='Per-page parsed markdown and artifact paths', null=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, help_text='Set by round-robin when control totals do not balance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to='tenancy.firmmembership')),
                ('document_source', models.ForeignKey(help_text='The live source row; may be removed later without losing this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_documents', to='configuration.documentsource')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='periods.accountingperiod')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_period_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Period Document',
                'verbose_name_plural': 'Period Documents',
                'db_table': 'period_document',
                'ordering': ['source_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationJob',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(help_text='Denormalized so the queue can serialize per client without a join', on_delete=django.db.models.deletion.CASCADE, related_name='classification_jobs', to='tenancy.client')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_jobs', to='periods.perioddocument')),
            ],
            options={
                'verbose_name': 'Classification Job',
                'verbose_name_plural': 'Classification Jobs',
                'db_table': 'classification_job',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodFieldValue',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(max_length=128)),
                ('field_label', models.CharField(max_length=255)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('value', models.CharField(blank=True, max_length=1000)),
                ('direction', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='periods.perioddocument')),
                ('extraction_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_values', to='configuration.extractionfield')),
                ('ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_values', to='ledger.ledgeraccount')),
                ('offset_ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offset_field_values', to='ledger.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Period Field Value',
                'verbose_name_plural': 'Period Field Values',
                'db_table': 'period_field_value',
                'ordering': ['field_key', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='PeriodManualJournalLine',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_line_key', models.CharField(help_text="Key into the period's frozen template lines", max_length=128)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('direction', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_journal_lines', to=settings.AUTH_USER_MODEL)),
                ('ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_journal_lines', to='ledger.ledgeraccount')),
                ('offset_ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offset_manual_journal_lines', to='ledger.ledgeraccount')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_journal_lines', to='periods.accountingperiod')),
            ],
            options={
                'verbose_name': 'Period Manual Journal Line',
                'verbose_name_plural': 'Period Manual Journal Lines',
                'db_table': 'period_manual_journal_line',
            },
        ),
        migrations.CreateModel(
            name='PeriodTransaction',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('line_number', models.PositiveIntegerField()),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('raw_date', models.CharField(blank=True, help_text='Date exactly as printed on the document', max_length=64)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Always positive; direction carries the sign', max_digits=15, null=True)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('is_manually_classified', models.BooleanField(default=False)),
                ('is_check', models.BooleanField(default=False)),
                ('check_number', models.CharField(blank=True, max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='periods.perioddocument')),
                ('ledger_account', models.ForeignKey(blank=True, help_text='Assigned by the classifier or edited by a reviewer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ledger.ledgeraccount')),
                ('offset_ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offset_transactions', to='ledger.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Period Transaction',
                'verbose_name_plural': 'Period Transactions',
                'db_table': 'period_transaction',
                'ordering': ['page_number', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='PeriodCheckDetail',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('check_number', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payee', models.TextField(blank=True)),
                ('memo', models.TextField(blank=True)),
                ('cleared_on', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_details', to='periods.perioddocument')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_details', to='periods.periodtransaction')),
            ],
            options={
                'verbose_name': 'Period Check Detail',
                'verbose_name_plural': 'Period Check Details',
                'db_table': 'period_check_detail',
                'ordering': ['page_number', 'check_number'],
            },
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['client', 'year', 'month'], name='accounting__client__073df6_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('client', 'year', 'month'), name='uniq_open_period_per_client_month'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='period_month_in_range'),
        ),
        migrations.AddIndex(
            model_name='perioddocument',
            index=models.Index(fields=['period', 'status'], name='period_docu_period__3677af_idx'),
        ),
        migrations.AddConstraint(
            model_name='perioddocument',
            constraint=models.UniqueConstraint(fields=('period', 'source_key'), name='uniq_document_per_period_source'),
        ),
        migrations.AddIndex(
            model_name='classificationjob',
            index=models.Index(fields=['client', 'status', 'created_at'], name='classificat_client__2506e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodfieldvalue',
            constraint=models.UniqueConstraint(fields=('document', 'field_key', 'page_number'), name='uniq_field_value_per_document_page'),
        ),
        migrations.AddConstraint(
            model_name='periodmanualjournalline',
            constraint=models.UniqueConstraint(fields=('period', 'template_line_key'), name='uniq_manual_line_per_period_template_line'),
        ),
        migrations.AddIndex(
            model_name='periodtransaction',
            index=models.Index(fields=['document', 'page_number'], name='period_tran_documen_d79ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='periodtransaction',
            index=models.Index(fields=['document', 'ledger_account'], name='period_tran_documen_7016bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodtransaction',
            constraint=models.UniqueConstraint(fields=('document', 'page_number', 'line_number'), name='uniq_transaction_position_per_document'),
        ),
        migrations.AddIndex(
            model_name='periodcheckdetail',
            index=models.Index(fields=['document', 'check_number'], name='period_chec_documen_5b9731_idx'),
        ),
    ]
