# Generated by Django 5.2.1 on 2026-09-04 07:48

import django.db.models.deletion
import storage.uploads
import v1.common.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Shown to whoever is configuring a source of this kind')),
                ('extraction_mode', models.CharField(choices=[('transactional', 'A list of transactions'), ('fields', 'Named values you configure')], max_length=16)),
                ('is_active', models.BooleanField(default=True, help_text='Retired categories stay for sources already using them, but drop out of the picker for new ones')),
                ('firm', models.ForeignKey(blank=True, help_text='Null for a system default, available to every firm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='tenancy.firm')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'db_table': 'document_category',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('extraction_notes', models.TextField(blank=True, help_text='Free text passed to the classifier as client-specific guidance')),
                ('reference_file', models.FileField(blank=True, help_text='An example document, for reference only — never extracted', max_length=500, null=True, upload_to=storage.uploads.upload_to_input_files_folder)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(help_text='What kind of document this is, and therefore how it is read', on_delete=django.db.models.deletion.PROTECT, related_name='document_sources', to='configuration.documentcategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sources', to='tenancy.client')),
                ('default_offset_account', models.ForeignKey(blank=True, help_text='Where the other side of each entry lands by default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offset_document_sources', to='ledger.ledgeraccount')),
                ('ledger_account', models.ForeignKey(blank=True, help_text='For transactional sources, the account the statement represents', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_sources', to='ledger.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Document Source',
                'verbose_name_plural': 'Document Sources',
                'db_table': 'document_source',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionField',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text='Identifier used in the extraction schema', max_length=128)),
                ('label', models.CharField(help_text='Human name shown in the UI', max_length=255)),
                ('prompt_hint', models.TextField(blank=True, help_text="Tells the extractor what to look for, e.g. 'Total employer taxes, bottom of the summary page'")),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('document_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='configuration.documentsource')),
                ('ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_fields', to='ledger.ledgeraccount')),
                ('offset_ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offset_extraction_fields', to='ledger.ledgeraccount')),
            ],
            options={
                'verbose_name': 'Extraction Field',
                'verbose_name_plural': 'Extraction Fields',
                'db_table': 'extraction_field',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JournalTemplate',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('adhoc', 'Ad hoc')], default='monthly', max_length=16)),
                ('entry_type', models.CharField(blank=True, max_length=64)),
                ('uses_extracted_fields', models.BooleanField(default=False, help_text='True when lines draw their amounts from extracted fields rather than fixed ledger accounts')),
                ('description', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_templates', to='tenancy.client')),
                ('sources', models.ManyToManyField(blank=True, related_name='journal_templates', to='configuration.documentsource')),
            ],
            options={
                'verbose_name': 'Journal Template',
                'verbose_name_plural': 'Journal Templates',
                'db_table': 'journal_template',
            },
        ),
        migrations.CreateModel(
            name='JournalTemplateLine',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount_source', models.CharField(choices=[('extracted_field', 'From an extracted field'), ('fixed', 'Fixed amount'), ('manual', 'Entered each period')], max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Required when amount_source is fixed', max_digits=15, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('extraction_field', models.ForeignKey(blank=True, help_text='Required when amount_source is extracted_field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_lines', to='configuration.extractionfield')),
                ('ledger_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_lines', to='ledger.ledgeraccount')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='configuration.journaltemplate')),
            ],
            options={
                'verbose_name': 'Journal Template Line',
                'verbose_name_plural': 'Journal Template Lines',
                'db_table': 'journal_template_line',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.UUIDField(default=v1.common.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('payload', models.JSONField(help_text='Frozen document sources, extraction fields, journal templates and lines')),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_versions', to='tenancy.client')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_config_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Config Version',
                'verbose_name_plural': 'Config Versions',
                'db_table': 'config_version',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('client', 'version'), name='uniq_config_version_per_client')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(fields=('firm', 'key'), name='uniq_category_key_per_firm'),
        ),
        migrations.AddIndex(
            model_name='documentsource',
            index=models.Index(fields=['client', 'is_active'], name='document_so_client__f3e720_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentsource',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='uniq_source_name_per_client'),
        ),
        migrations.AddConstraint(
            model_name='extractionfield',
            constraint=models.UniqueConstraint(fields=('document_source', 'key'), name='uniq_field_key_per_source'),
        ),
        migrations.AddIndex(
            model_name='journaltemplate',
            index=models.Index(fields=['client', 'frequency'], name='journal_tem_client__cd771c_idx'),
        ),
        migrations.AddConstraint(
            model_name='journaltemplate',
            constraint=models.UniqueConstraint(fields=('client', 'frequency', 'name'), name='uniq_template_name_per_client_frequency'),
        ),
    ]
