# Generated by Django 5.2.1 on 2025-07-01 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimAICClient',
            fields=[
                ('client_id', models.AutoField(primary_key=True,
                                               serialize=False, verbose_name='Client ID')),
                ('client_name', models.CharField(
                    max_length=255, verbose_name='Client Name')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=2,
                                           verbose_name='State Abbreviation')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Updated At')),
                ('input_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Input User (Admin)')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'dim_aic_client',
            },
        ),
        migrations.CreateModel(
            name='DimAICClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('COA', 'Chart of Accounts'), ('VENDOR_LIST', 'Vendor List'), (
                    'GL_HISTORY', 'GL History')], max_length=20, verbose_name='Document Type')),
                ('file', models.FileField(help_text='File will be stored in local media folder. Future support for S3/Azure.',
                                          upload_to='client_documents/', verbose_name='Document File')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='documents', to='user.dimaicclient', verbose_name='Client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'db_table': 'client_documents',
            },
        ),
        migrations.CreateModel(
            name='DimAICCustomer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True,
                                                 serialize=False, verbose_name='Customer ID')),
                ('customer_secure_id', models.CharField(editable=False,
                                                        max_length=9, verbose_name='Customer Secure ID')),
                ('customer_name', models.CharField(
                    max_length=255, verbose_name='Customer Name')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state_abrevation', models.CharField(
                    max_length=2, verbose_name='State Abbrevation')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('registration_complete', models.BooleanField(
                    default=False, help_text='Becomes True after first SSO login')),
                ('invite_token', models.CharField(
                    blank=True, help_text='Invite token for registration', max_length=255, null=True)),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Updated At')),
                ('input_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
                ('user', models.OneToOneField(help_text='Link to Django user for authentication and permissions', on_delete=django.db.models.deletion.CASCADE,
                                              related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Linked Django User')),
            ],
            options={
                'verbose_name': 'AIC Customer',
                'verbose_name_plural': 'AIC Customers',
                'db_table': 'dim_aic_customer',
            },
        ),
        migrations.AddField(
            model_name='dimaicclient',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='clients', to='user.dimaiccustomer', verbose_name='Customer'),
        ),
        migrations.CreateModel(
            name='DimAICUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True,
                                             serialize=False, verbose_name='User ID')),
                ('username', models.CharField(max_length=8, verbose_name='Username')),
                ('first_name', models.CharField(
                    max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(
                    max_length=100, verbose_name='Last Name')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created At')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='user.dimaiccustomer', verbose_name='Customer ID')),
            ],
            options={
                'verbose_name': 'AIC User',
                'verbose_name_plural': 'AIC Users',
                'db_table': 'dim_aic_user',
            },
        ),
        migrations.AddField(
            model_name='dimaicclient',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='assigend_clients', to='user.dimaicuser', verbose_name='Assigned User'),
        ),
        migrations.CreateModel(
            name='DimAICContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[
                 ('phone', 'phone'), ('email', 'email')], max_length=5, verbose_name='Contact Type')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact')),
                ('reg_flg', models.BooleanField(verbose_name='Registration Flag')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Updated At')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='user.dimaicclient', verbose_name='Client ID')),
                ('input_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 to=settings.AUTH_USER_MODEL, verbose_name='Input User')),
            ],
            options={
                'verbose_name': 'AIC Contact',
                'verbose_name_plural': 'AIC Contacts',
                'db_table': 'dim_aic_contact',
                'unique_together': {('client_id', 'contact_type')},
            },
        ),
    ]
