# Generated by Django 4.2.23 on 2025-07-12 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimaiccustomer',
            old_name='user',
            new_name='system_user',
        ),
        migrations.AddField(
            model_name='dimaicclient',
            name='id',
            field=models.CharField(
                default=1, max_length=255, verbose_name='Client Assigned ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimaicuser',
            name='system_user',
            field=models.OneToOneField(default=1, help_text='Link to Django user for authentication and permissions',
                                       on_delete=django.db.models.deletion.CASCADE, related_name='User_profile', to=settings.AUTH_USER_MODEL, verbose_name='Linked Django User'),
            preserve_default=False,
        ),
    ]
