# Generated by Django 4.2.23 on 2025-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_dimaiccustomer_system_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimaiccustomer',
            name='invite_token',
        ),
        migrations.AddField(
            model_name='dimaiccustomer',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='dimaicuser',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
