# Generated by Django 4.2.23 on 2025-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_dimaicclient_id_dimaicassistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimaicassistant',
            name='response_format_schema_path',
        ),
        migrations.AddField(
            model_name='dimaicassistant',
            name='response_schema',
            field=models.JSONField(
                default={}, help_text='JSON schema response format', verbose_name='Response Format Schema'),
            preserve_default=False,
        ),
    ]
