# Generated by Django 4.2.23 on 2025-07-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_dimaicassistant_response_format_schema_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimaicclient',
            old_name='id',
            new_name='temp_client_id',
        ),
        migrations.RenameField(
            model_name='dimaicclient',
            old_name='client_id',
            new_name='temp_id',
        ),
    ]
