# Generated by Django 4.2.28 on 2026-02-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_dimaicaccountant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimaicclient',
            name='allow_review',
            field=models.BooleanField(default=False, verbose_name='Allow Doucment HITL Review'),
        ),
    ]
