# Generated by Django 5.2.1 on 2026-09-03 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientClassifierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_id', models.CharField(blank=True, max_length=128)),
                ('vector_store_id', models.CharField(blank=True, max_length=128)),
                ('model_name', models.CharField(default='gpt-4o', max_length=64)),
                ('response_schema', models.JSONField(blank=True, null=True)),
                ('special_rules', models.TextField(blank=True, help_text='Client-specific guidance appended to the classifier prompt')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_profile', to='tenancy.client')),
                ('provisioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_classifier_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Classifier Profile',
                'verbose_name_plural': 'Client Classifier Profiles',
                'db_table': 'client_classifier_profile',
            },
        ),
        migrations.CreateModel(
            name='LedgerAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to='tenancy.firm')),
            ],
            options={
                'verbose_name': 'Ledger Account Type',
                'verbose_name_plural': 'Ledger Account Types',
                'db_table': 'ledger_account_type',
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('account_class', models.CharField(blank=True, choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=32)),
                ('sub_class', models.CharField(blank=True, help_text='e.g. Cash, Fixed Assets, Current Liabilities', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='tenancy.client')),
                ('account_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='ledger.ledgeraccounttype')),
            ],
            options={
                'verbose_name': 'Ledger Account',
                'verbose_name_plural': 'Ledger Accounts',
                'db_table': 'ledger_account',
                'ordering': ['account_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='ledgeraccounttype',
            constraint=models.UniqueConstraint(fields=('firm', 'code'), name='uniq_account_type_code_per_firm'),
        ),
        migrations.AddIndex(
            model_name='ledgeraccount',
            index=models.Index(fields=['client', 'is_active'], name='ledger_acco_client__e75e9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('client', 'account_number'), name='uniq_account_number_per_client'),
        ),
    ]
