name: CI/CD Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Authenticate to Tailscale
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Server to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.TAILSCALE_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Dev Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.TAILSCALE_SERVER_IP }} << 'EOF'
            echo "Starting Backend Deployment..."
            
            # Define paths
            BACKEND_PATH="/home/aicounting/aicounting-backend"
            DEPLOYMENT_COMMAND_PATH="/home/aicounting/aicounting-serve"

            # Pull latest frontend code
            cd "$BACKEND_PATH"
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S git pull

            # Run deployment script
            cd "$DEPLOYMENT_COMMAND_PATH"
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S ./deploy.sh --env=dev --server=apache --build-backend

          EOF
